import { NextRequest, NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth'
import { UserRole } from '@/types/auth'
import { getServerSession } from 'next-auth'
import { generateDailyReport } from '@/lib/reports'

/**
 * GET /api/admin/reports/daily
 * Generate daily report of newly created workers
 */
export async function GET(request: NextRequest) {
  try {
    // Require ADMIN role
    await requireRole(UserRole.ADMIN)

    // Get the current user's name for "Generated by" line
    const session = await getServerSession()
    const generatedBy = session?.user?.name || 'Admin'

    // Generate the report
    const { buffer, filename } = await generateDailyReport(generatedBy)

    // Return PDF with appropriate headers
    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': buffer.length.toString(),
      },
    })

  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : 'Unknown error'
  

    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate daily report',
        message: errorMsg,
      },
      { status: 500 }
    )
  }
}
