// pnpm --filter @remonta/db localities:build --release=YYYYMM --src=<unzipped G-NAF>
//
// Offline. Reads a G-NAF release and writes, under packages/db/data/:
//   au_localities.csv        one row per suburb-postcode pair (committed)
//   au_localities.meta.json  release, checksum and the selection report (committed)
//   ATTRIBUTION.md           the licence attribution (committed)
// Commit all three together; the PR diff is then exactly the suburbs that changed.
import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toCsv } from './csv.js'
import { readRelease } from './gnaf.js'
import { selectLocalities, type SelectionReport } from './select.js'

export const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'data')

export interface LocalitiesMeta {
  sourceVersion: string
  dataset: string
  rows: number
  csvSha256: string
  report: SelectionReport
}

export function sourceVersionFor(release: string): string {
  if (!/^20[0-9]{2}(0[1-9]|1[0-2])$/.test(release)) throw new Error(`--release must be YYYYMM, got ${release}`)
  return `GNAF-${release}`
}

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

export async function build(opts: { src: string; release: string; outDir?: string; log?: (m: string) => void }) {
  const log = opts.log ?? (() => {})
  const sourceVersion = sourceVersionFor(opts.release)
  const release = await readRelease(opts.src, log)
  const { rows, report } = selectLocalities(release.localities, release.centroids, release.addressPostcodes)
  const csv = toCsv(rows)
  const meta: LocalitiesMeta = {
    sourceVersion,
    dataset: 'Geoscape G-NAF (GDA2020, PSV), data.gov.au',
    rows: rows.length,
    csvSha256: sha256(csv),
    report,
  }
  const outDir = opts.outDir ?? DATA_DIR
  await mkdir(outDir, { recursive: true })
  await writeFile(join(outDir, 'au_localities.csv'), csv, 'utf8')
  await writeFile(join(outDir, 'au_localities.meta.json'), JSON.stringify(meta, null, 2) + '\n', 'utf8')
  await writeFile(join(outDir, 'ATTRIBUTION.md'), attribution(sourceVersion), 'utf8')
  return { meta, addressesRead: release.addressesRead }
}

function attribution(sourceVersion: string): string {
  return `# Attribution

\`au_localities.csv\` is derived from **Geoscape G-NAF** (${sourceVersion}), published on
data.gov.au: https://data.gov.au/data/dataset/geocoded-national-address-file-g-naf

> Incorporates or developed using G-NAF ©Geoscape Australia licensed by the Commonwealth
> of Australia under the Open Geo-coded National Address File (G-NAF) End User Licence
> Agreement.

The Open G-NAF EULA also restricts use for sending unsolicited mail to addresses. This
file holds suburb names, postcodes and centroids only -- no addresses.

Generated by \`scripts/localities/build.ts\`; do not edit by hand.
`
}

function arg(name: string): string | undefined {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`))
  return hit?.slice(name.length + 3)
}

async function main() {
  const src = arg('src')
  const release = arg('release')
  if (!src || !release) {
    console.error('usage: localities:build --release=YYYYMM --src=<unzipped G-NAF folder>')
    process.exit(2)
  }
  const started = Date.now()
  const { meta, addressesRead } = await build({ src, release, log: (m) => console.error(m) })
  const r = meta.report
  console.log(`\n${meta.sourceVersion}: ${r.localities} localities, ${addressesRead} addresses read`)
  console.log(`rows written: ${meta.rows}`)
  console.log(`kept by class: ${JSON.stringify(r.keptByClass)}`)
  console.log(`dropped by reason: ${JSON.stringify(r.droppedByReason)}`)
  console.log(`dropped by class: ${JSON.stringify(r.droppedByClass)}`)
  console.log(`multi-postcode localities: ${r.multiPostcode.map((m) => `${m.suburb} ${m.state} ${m.postcodes.join('/')}`).join('; ') || 'none'}`)
  console.log(`PRIMARY_POSTCODE fallbacks (review): ${r.primaryPostcodeFallbacks.length}`)
  for (const f of r.primaryPostcodeFallbacks) console.log(`  ${f.suburb} ${f.state} ${f.postcode}`)
  if (r.invalidAddressPostcodes.length) console.log(`invalid address postcodes: ${JSON.stringify(r.invalidAddressPostcodes)}`)
  console.log(`done in ${Math.round((Date.now() - started) / 1000)} s -> ${DATA_DIR}`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((e) => {
    console.error(e instanceof Error ? e.message : e)
    process.exit(1)
  })
}
