import { NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth'
import { UserRole } from '@/types/auth'
import { authPrisma as prisma } from '@/lib/auth-prisma'
import { getServerSession } from 'next-auth'
import jsPDF from 'jspdf'

interface WeeklyStats {
  weekStart: string
  weekEnd: string
  weekNumber: number
  count: number
}

/**
 * Get the start of the current week (Monday)
 */
function getStartOfWeek(date: Date): Date {
  const d = new Date(date)
  const day = d.getDay()
  const diff = d.getDate() - day + (day === 0 ? -6 : 1)
  d.setDate(diff)
  d.setHours(0, 0, 0, 0)
  return d
}

/**
 * Get the start of the year
 */
function getStartOfYear(year: number): Date {
  return new Date(year, 0, 1, 0, 0, 0, 0)
}

/**
 * Format date as YYYY-MM-DD
 */
function formatDate(date: Date): string {
  return date.toISOString().split('T')[0]
}

/**
 * Format date range for display
 */
function formatDateRange(weekStart: string, weekEnd: string): string {
  const start = new Date(weekStart)
  const end = new Date(weekEnd)
  const options: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric' }
  return `${start.toLocaleDateString('en-US', options)} - ${end.toLocaleDateString('en-US', options)}`
}

/**
 * GET /api/admin/reports/worker-statistics
 * Generate PDF report of worker statistics by service category
 */
export async function GET() {
  try {
    await requireRole(UserRole.ADMIN)

    const session = await getServerSession()
    const generatedBy = session?.user?.name || 'Admin'

    const now = new Date()
    const currentYear = now.getFullYear()
    const startOfYear = getStartOfYear(currentYear)
    const startOfCurrentWeek = getStartOfWeek(now)

    // Get total workers count
    const totalWorkers = await prisma.workerProfile.count()

    // Get workers added this week
    const addedThisWeek = await prisma.workerProfile.count({
      where: {
        createdAt: {
          gte: startOfCurrentWeek,
        },
      },
    })

    // Get workers grouped by their service category
    const serviceStats = await prisma.workerService.groupBy({
      by: ['categoryName'],
      _count: {
        workerProfileId: true,
      },
      orderBy: {
        _count: {
          workerProfileId: 'desc',
        },
      },
    })

    // Get weekly breakdown since start of year
    const weeklyBreakdown: WeeklyStats[] = []
    let weekStart = getStartOfWeek(startOfYear)
    let weekNumber = 1

    // Handle days before first Monday of the year
    if (startOfYear.getDay() !== 1) {
      const dayOfWeek = startOfYear.getDay()
      const daysUntilMonday = dayOfWeek === 0 ? 1 : 8 - dayOfWeek
      weekStart = new Date(startOfYear)
      weekStart.setDate(startOfYear.getDate() + daysUntilMonday)
      weekStart.setHours(0, 0, 0, 0)

      const workersBeforeFirstMonday = await prisma.workerProfile.count({
        where: {
          createdAt: {
            gte: startOfYear,
            lt: weekStart,
          },
        },
      })

      if (workersBeforeFirstMonday > 0 || startOfYear < weekStart) {
        weeklyBreakdown.push({
          weekStart: formatDate(startOfYear),
          weekEnd: formatDate(new Date(weekStart.getTime() - 1)),
          weekNumber: 0,
          count: workersBeforeFirstMonday,
        })
      }
    }

    // Loop through each week
    while (weekStart <= now) {
      const weekEnd = new Date(weekStart)
      weekEnd.setDate(weekEnd.getDate() + 6)
      weekEnd.setHours(23, 59, 59, 999)

      const actualEndDate = weekEnd > now ? now : weekEnd

      const count = await prisma.workerProfile.count({
        where: {
          createdAt: {
            gte: weekStart,
            lte: actualEndDate,
          },
        },
      })

      weeklyBreakdown.push({
        weekStart: formatDate(weekStart),
        weekEnd: formatDate(actualEndDate),
        weekNumber,
        count,
      })

      weekStart = new Date(weekStart)
      weekStart.setDate(weekStart.getDate() + 7)
      weekNumber++
    }

    // Generate PDF
    const doc = new jsPDF()

    // Title
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('Worker Statistics Report', 14, 20)

    // Generated by line
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const generatedDate = new Date()
    const formattedDate = generatedDate.toLocaleDateString('en-US', {
      month: 'short',
      day: '2-digit',
      year: 'numeric',
    }).replace(',', '')
    const formattedTime = generatedDate.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: true,
    })
    doc.text(`Generated by ${generatedBy} on ${formattedDate} ${formattedTime}`, 14, 28)

    // Summary section
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Summary', 14, 42)

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Total Workers: ${totalWorkers.toLocaleString()}`, 14, 50)
    doc.text(`Added This Week: ${addedThisWeek.toLocaleString()}`, 14, 58)

    // Workers by Service Category section
    let currentY = 74
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text('Workers by Main Service', 14, currentY)
    currentY += 10

    // Table header for services
    doc.setFillColor(220, 230, 241)
    doc.rect(14, currentY - 5, 182, 8, 'F')
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Service Category', 16, currentY)
    doc.text('Count', 140, currentY)
    doc.text('Percentage', 165, currentY)
    currentY += 8

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)

    serviceStats.forEach((service, index) => {
      if (currentY > 270) {
        doc.addPage()
        currentY = 20
      }

      if (index % 2 === 1) {
        doc.setFillColor(248, 249, 250)
        doc.rect(14, currentY - 5, 182, 8, 'F')
      }

      const percentage = totalWorkers > 0
        ? ((service._count.workerProfileId / totalWorkers) * 100).toFixed(1)
        : '0'

      doc.text(service.categoryName, 16, currentY)
      doc.text(service._count.workerProfileId.toLocaleString(), 140, currentY)
      doc.text(`${percentage}%`, 165, currentY)
      currentY += 8
    })

    // Weekly Breakdown section
    currentY += 10
    if (currentY > 240) {
      doc.addPage()
      currentY = 20
    }

    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(`Weekly Breakdown (Since Start of ${currentYear})`, 14, currentY)
    currentY += 10

    // Table header for weekly breakdown
    doc.setFillColor(220, 230, 241)
    doc.rect(14, currentY - 5, 182, 8, 'F')
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text('Week', 16, currentY)
    doc.text('Date Range', 60, currentY)
    doc.text('Workers Added', 140, currentY)
    currentY += 8

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)

    weeklyBreakdown.forEach((week, index) => {
      if (currentY > 270) {
        doc.addPage()
        currentY = 20
      }

      if (index % 2 === 1) {
        doc.setFillColor(248, 249, 250)
        doc.rect(14, currentY - 5, 182, 8, 'F')
      }

      const weekLabel = week.weekNumber === 0 ? 'Pre-Week 1' : `Week ${week.weekNumber}`
      doc.text(weekLabel, 16, currentY)
      doc.text(formatDateRange(week.weekStart, week.weekEnd), 60, currentY)
      doc.text(week.count.toLocaleString(), 140, currentY)
      currentY += 8
    })

    // Generate PDF as buffer
    const pdfBuffer = Buffer.from(doc.output('arraybuffer'))

    const reportDate = new Date().toLocaleDateString('en-US', {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric',
    })
    const filename = `Worker Statistics Report ${reportDate}.pdf`

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': pdfBuffer.length.toString(),
      },
    })
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : 'Unknown error'

    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate worker statistics report',
        message: errorMsg,
      },
      { status: 500 }
    )
  }
}
