import { authPrisma as prisma } from '@/lib/auth-prisma'
import jsPDF from 'jspdf'

/**
 * Transform WorkerService records to get primary service
 */
function getPrimaryService(workerServices: Array<{ categoryName: string }>): string {
  if (workerServices.length === 0) return 'N/A'
  return workerServices[0].categoryName
}

/**
 * Generate a PDF report of newly created workers
 * @param generatedBy - Name of the person generating the report
 * @param startDate - Start date for filtering workers
 * @param endDate - End date for filtering workers (optional, defaults to now)
 * @param reportTitle - Title of the report
 * @returns PDF buffer
 */
export async function generateWorkerReport(
  generatedBy: string,
  startDate: Date,
  endDate: Date = new Date(),
  reportTitle: string = 'Profile Submissions'
): Promise<Buffer> {
  // Fetch workers created in the date range
  const workers = await prisma.workerProfile.findMany({
    where: {
      createdAt: {
        gte: startDate,
        lte: endDate
      }
    },
    select: {
      firstName: true,
      lastName: true,
      state: true,
      workerServices: {
        select: {
          categoryName: true,
        }
      },
    },
    orderBy: {
      createdAt: 'desc'
    }
  })

  // Generate PDF
  const doc = new jsPDF()

  // Title
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(reportTitle, 14, 20)

  // Generated by line
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const generatedDate = new Date()
  const formattedDate = generatedDate.toLocaleDateString('en-US', {
    month: 'short',
    day: '2-digit',
    year: 'numeric'
  }).replace(',', '')
  const formattedTime = generatedDate.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  })
  doc.text(`Generated by ${generatedBy} on ${formattedDate} ${formattedTime}`, 14, 28)

  // Record count
  doc.setFontSize(10)
  doc.text(`Record Count : ${workers.length}`, 14, 38)

  // Table header
  const headerY = 50
  doc.setFillColor(220, 230, 241) // Light blue background
  doc.rect(14, headerY - 5, 182, 8, 'F')

  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text('Full Name', 16, headerY)
  doc.text('Primary Service', 75, headerY)
  doc.text('State/Region/Province', 145, headerY)

  // Table rows
  let currentY = headerY + 8
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)

  workers.forEach((worker, index) => {
    // Add new page if needed
    if (currentY > 270) {
      doc.addPage()
      currentY = 20
    }

    const fullName = `${worker.firstName} ${worker.lastName}`
    const primaryService = getPrimaryService(worker.workerServices)
    const state = worker.state || 'N/A'

    // Alternate row background
    if (index % 2 === 1) {
      doc.setFillColor(248, 249, 250) // Light gray
      doc.rect(14, currentY - 5, 182, 8, 'F')
    }

    doc.text(fullName, 16, currentY)
    doc.text(primaryService, 75, currentY)
    doc.text(state, 145, currentY)

    currentY += 8
  })

  // Generate PDF as buffer
  const pdfBuffer = Buffer.from(doc.output('arraybuffer'))
  return pdfBuffer
}

/**
 * Generate daily report of newly created workers
 * @param generatedBy - Name of the person generating the report
 * @returns Object with PDF buffer and filename
 */
export async function generateDailyReport(generatedBy: string): Promise<{
  buffer: Buffer
  filename: string
}> {
  // Calculate date range for today (start of day to now)
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  const formattedDate = new Date().toLocaleDateString('en-US', {
    month: '2-digit',
    day: '2-digit',
    year: 'numeric'
  })

  const buffer = await generateWorkerReport(
    generatedBy,
    today,
    new Date(),
    'Daily Profile Submissions'
  )

  return {
    buffer,
    filename: `Daily Profile Submissions ${formattedDate}.pdf`
  }
}

/**
 * Generate weekly report of newly created workers
 * @param generatedBy - Name of the person generating the report
 * @returns Object with PDF buffer and filename
 */
export async function generateWeeklyReport(generatedBy: string): Promise<{
  buffer: Buffer
  filename: string
}> {
  // Calculate date range for last 7 days
  const today = new Date()
  const weekAgo = new Date()
  weekAgo.setDate(today.getDate() - 7)
  weekAgo.setHours(0, 0, 0, 0)

  const formattedDate = new Date().toLocaleDateString('en-US', {
    month: '2-digit',
    day: '2-digit',
    year: 'numeric'
  })

  const buffer = await generateWorkerReport(
    generatedBy,
    weekAgo,
    new Date(),
    'Weekly Profile Submissions'
  )

  return {
    buffer,
    filename: `Weekly Profile Submissions ${formattedDate}.pdf`
  }
}
