#!/usr/bin/env bash
# Set up a fresh machine to continue this repository's work (written 2026-09-30, before
# a reformat). Run it from Git Bash (Windows) or any shell, from the repository root:
#
#   git clone https://github.com/remontasupport/remontamarketplace.git
#   cd remontamarketplace
#   git checkout main                       # or whichever branch aidlc-docs/aidlc-state.md names
#   bash scripts/setup-new-machine.sh        # add --verify to run every quality gate at the end
#
# It is idempotent: every step checks before it acts, so rerun it after fixing whatever
# it asked you to fix. It never prints a secret. Steps:
#   0. What must be installed by hand (it checks and tells you what is missing)
#   1. The three environment files that are NOT in git (restore them from your backup)
#   2. pnpm install
#   3. The local PostGIS database in Docker, migrated, with the suburb list and the catalogue
#   4. (--verify) the quality gates
#   5. Where to resume the AI-DLC
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
VERIFY=0; [ "${1:-}" = "--verify" ] && VERIFY=1
ok()   { printf '  \033[32mok\033[0m   %s\n' "$*"; }
todo() { printf '  \033[33mTODO\033[0m %s\n' "$*"; }
fail() { printf '  \033[31mFAIL\033[0m %s\n' "$*"; }
say()  { printf '\n== %s\n' "$*"; }
missing=0

# ---------------------------------------------------------------------------
say "0. Tools (install by hand what is missing, then rerun)"
if command -v git >/dev/null; then ok "git $(git --version | awk '{print $3}')"; else fail "git: https://git-scm.com"; missing=1; fi
if command -v node >/dev/null; then
  v=$(node -v | tr -d v); major=${v%%.*}
  if [ "$major" -ge 20 ]; then ok "node $v"; else fail "node $v is too old: need 20.9+ (https://nodejs.org, LTS)"; missing=1; fi
else fail "node: install Node 20 LTS from https://nodejs.org"; missing=1; fi
if command -v pnpm >/dev/null; then ok "pnpm $(pnpm -v) (the repository pins 9.15.9 via packageManager)"; else todo "pnpm: run  corepack enable && corepack prepare pnpm@9.15.9 --activate"; missing=1; fi
if command -v docker >/dev/null && docker ps >/dev/null 2>&1; then ok "docker engine running"; else todo "Docker Desktop: install from https://www.docker.com/products/docker-desktop and start it (needed for the local database and the api tests)"; fi
if command -v gcloud >/dev/null; then ok "gcloud (optional locally; Cloud Shell in the browser also works)"; else todo "gcloud (optional): https://cloud.google.com/sdk/docs/install -- or use Cloud Shell in the console"; fi
if command -v vercel >/dev/null || [ -d node_modules ]; then ok "vercel CLI comes with npx once dependencies are installed"; fi
[ "$missing" = "1" ] && { echo; echo "Install the items marked FAIL/TODO above, then rerun this script."; exit 1; }

# ---------------------------------------------------------------------------
say "1. Environment files (gitignored; restore from your backup, never commit them)"
envmissing=0
for f in apps/app/.env apps/app/.env.local apps/api/.env; do
  if [ -f "$f" ]; then ok "$f present ($(grep -cE '^[A-Z_]+=' "$f") variables)"; else fail "$f is missing -- restore it from the backup you made before the reformat"; envmissing=1; fi
done
if [ -f apps/api/.env ]; then
  host=$(grep -E '^AUTH_DATABASE_URL=' apps/api/.env | cut -d= -f2- | tr -d '"' | sed -E 's#^[a-z]+://([^@/]*@)?([^/:?]+).*#\2#')
  case "$host" in localhost|127.0.0.1) ok "apps/api/.env AUTH_DATABASE_URL points at the LOCAL database (required: the api tests refuse anything else)";; *) fail "apps/api/.env AUTH_DATABASE_URL must point at localhost (see CLAUDE.md 'apps/api'); it points at: $host";; esac
fi
if [ "$envmissing" = "1" ]; then
  echo
  echo "Without apps/app/.env and apps/api/.env nothing can run locally. Restore them, then rerun."
  echo "(apps/app/.env is the production-pointing copy used by the app; apps/api/.env holds the api's secrets"
  echo " and its REHEARSAL_DATABASE_URL; apps/app/.env.local holds the Zoho/Upstash/Resend values and the rehearsal strings.)"
  exit 1
fi

# ---------------------------------------------------------------------------
say "2. Dependencies"
if [ -d node_modules ] && [ -d apps/api/node_modules ]; then ok "node_modules present (run 'pnpm install' yourself if the lockfile changed)"; else pnpm install --frozen-lockfile && ok "pnpm install done (Prisma clients generated by postinstall)"; fi

# ---------------------------------------------------------------------------
say "3. Local PostGIS database (Docker container remonta-s1-pg, port 55432, db s1test)"
if ! docker ps >/dev/null 2>&1; then
  todo "Docker is not running: start Docker Desktop and rerun to create the database. Skipping."
else
  export AUTH_DATABASE_URL=postgresql://postgres:postgres@localhost:55432/s1test
  export DIRECT_DATABASE_URL=$AUTH_DATABASE_URL
  if docker ps -a --format '{{.Names}}' | grep -qx remonta-s1-pg; then
    docker start remonta-s1-pg >/dev/null; ok "container remonta-s1-pg exists (started)"
  else
    docker run -d --name remonta-s1-pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=s1test -p 55432:5432 postgis/postgis:16-3.4 >/dev/null && ok "container remonta-s1-pg created"
  fi
  for i in $(seq 1 30); do docker exec remonta-s1-pg pg_isready -U postgres >/dev/null 2>&1 && break; sleep 2; done
  docker exec remonta-s1-pg pg_isready -U postgres >/dev/null 2>&1 && ok "database accepting connections" || { fail "database did not come up"; exit 1; }

  echo "  migrating (every migration, PostGIS included)..."
  pnpm --filter @remonta/db run migrate:deploy >/dev/null 2>&1 && ok "migrations applied" || { fail "migrate:deploy failed -- run it by hand to see why: pnpm --filter @remonta/db run migrate:deploy"; exit 1; }

  count=$(docker exec remonta-s1-pg psql -U postgres -d s1test -tAc 'select count(*) from au_localities' 2>/dev/null | tr -d ' ')
  if [ "${count:-0}" -gt 15000 ]; then ok "suburb list loaded ($count localities)"; else
    echo "  loading the suburb list (dry run for the plan hash, then apply)..."
    plan=$(pnpm --filter @remonta/db localities:refresh 2>/dev/null | grep -oE 'expect=[0-9a-f]+' | cut -d= -f2 | head -1)
    if [ -n "$plan" ]; then pnpm --filter @remonta/db localities:refresh --apply --expect="$plan" --by=setup >/dev/null 2>&1 && ok "suburb list applied (plan $plan)" || fail "localities:refresh --apply failed"; else fail "no plan hash from the dry run"; fi
  fi
  cats=$(docker exec remonta-s1-pg psql -U postgres -d s1test -tAc 'select count(*) from "Category"' 2>/dev/null | tr -d ' ')
  if [ "${cats:-0}" -gt 0 ]; then ok "service catalogue seeded ($cats categories)"; else
    docker exec -i remonta-s1-pg psql -U postgres -d s1test < packages/db/scripts/local/seed-catalogue.sql >/dev/null 2>&1 && ok "service catalogue seeded" || fail "seed-catalogue.sql failed"
  fi
fi

# ---------------------------------------------------------------------------
if [ "$VERIFY" = "1" ]; then
  say "4. Quality gates (this takes several minutes)"
  export TEST_DATABASE_URL=postgresql://postgres:postgres@localhost:55432/s1test
  for p in app web schemas api-contract form-engine infra api; do
    if pnpm --filter @remonta/$p run quality >/dev/null 2>&1; then ok "@remonta/$p"; else fail "@remonta/$p -- run: pnpm --filter @remonta/$p run quality"; fi
  done
fi

# ---------------------------------------------------------------------------
say "5. Resume"
cat <<'EOF'
  The AI-DLC record is in the repository:
    aidlc-docs/aidlc-state.md      <- start here: "Resume here" then "PENDING RIGHT NOW"
    aidlc-docs/audit.md            <- every instruction given, verbatim
    aidlc-docs/archive/...         <- finished cycles: plans, designs, runbooks, summaries
    .aidlc-rule-details/, .brd/    <- the method's rules and the business record
    CLAUDE.md                      <- how to work in this repository

  Open Claude Code in this folder and say:  continue the AI-DLC
  It reads aidlc-state.md and picks up where the last session stopped.

  Also on the new machine, when needed:
    npx vercel login && npx vercel link --cwd apps/app --yes --project remonta-app   (Vercel CLI)
    gcloud auth login                                                               (or use Cloud Shell)
EOF
